=== JoyWonderful/blog-data-recovery/src/config.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",

    "title": "blog",
    "description": "Config definitions for my blog.",
    "type": "object",
    "properties": {
        "$schema": {
            "type": "string"
        },
        
        "title": {
            "description": "The title for your site.",
            "type": "string"
        },
        "subtitle": {
            "description": "The subtitle for your site. (bio, description, .etc)",
            "type": "string"
        },
        "author": {
            "description": "The author's name.",
            "type": "string"
        },
        "license_default": {
            "description": "The default license. The identifier follows https://spdx.org/licenses/.",
            "type": "string",
            "examples": ["CC-BY-4.0", "CC-BY-SA-4.0", "CC-BY-ND-4.0",
                         "CC-BY-NC-4.0", "CC-BY-NC-SA-4.0", "CC-BY-NC-ND-4.0",
                         "GFDL-1.3-or-later", "CC0-1.0", "CC-PDM-1.0"]
        },
        "lang": {
            "description": "Language for your site. (Used for html.lang)",
            "type": "string"
        },
        "favicon": {
            "description": "The url to your site favicon.",
            "type": "string"
        },
        "menu": {
            "description": "Menu entries for your site.",
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "icon": {
                        "description": "The fontawesome icon for the entry. (Full class name, `fa-fw` will be added automatically.)\n e.g. `fa fa-home`, `far fa-folder`",
                        "type": "string",
                        "pattern": "^fa[srb]? fa-.*$"
                    },
                    "name": {
                        "description": "The name displayed for the entry.",
                        "type": "string"
                    },
                    "href": {
                        "description": "The `href` attribute for the `<a>` element. Can be empty if you don't want to create `<a>` element.",
                        "type": "string"
                    }
                },
                "required": ["icon", "name"],
                "additionalProperties": false
            },
            "examples": [[
                {"icon": "fa fa-home", "name": "首页", "href": "/"},
                {"icon": "fa fa-rectangle-list", "name": "分类", "href": "/categories"},
                {"icon": "fa fa-tags", "name": "标签", "href": "/tags"},
                {"icon": "fa fa-box-archive", "name": "存档", "href": "/archives"}
            ]]
        },
        "menu_more": {
            "description": "More menu entries for your site. This will be collapsed.",
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "icon": {
                        "description": "The fontawesome icon for the entry. (Full class name, `fa-fw` will be added automatically.)\n e.g. `fa fa-home`, `far fa-folder`",
                        "type": "string",
                        "pattern": "^fa[srb]? fa-.*$"
                    },
                    "name": {
                        "description": "The name displayed for the entry.",
                        "type": "string"
                    },
                    "href": {
                        "description": "The `href` attribute for the `<a>` element. Can be empty if you don't want to create `<a>` element.",
                        "type": "string"
                    }
                },
                "required": ["icon", "name"],
                "additionalProperties": false
            },
            "examples": [[
                {"icon": "far fa-address-book", "name": "友情链接", "href": "/friends"},
                {"icon": "far fa-comments", "name": "留言簿", "href": "/guestbook"},
                {"icon": "fa fa-info", "name": "关于", "href": "/about"}
            ]]
        },

        "posts_path": {
            "description": "Your path for posts. (Used for a.href in posts.)",
            "type": "string",
            "default": "/posts"
        },
        "archives_path": {
            "description": "Your path for archives. (Used for a.href in posts.)",
            "type": "string",
            "default": "/archives"
        },
        "categories_path": {
            "description": "Your path for categories. (Used for a.href in posts.)",
            "type": "string",
            "default": "/categories"
        },
        "tags_path": {
            "description": "Your path for tags. (Used for a.href in posts.)",
            "type": "string",
            "default": "/tags"
        },

        "post_per_page": {
            "description": "Amount of displayed posts on per page.(At / (home))",
            "type": "integer",
            "default": 10
        },
        "archives_post_per_page": {
            "description": "Amount of displayed posts on per page.(At /archives)",
            "type": "integer",
            "default": 10
        },

        "tags_cloud": {
            "description": "Configurations for tags cloud.",
            "type": "object",
            "properties": {
                "min_font_size": {
                    "description": "The min font size. Unit: px.",
                    "type": "number",
                    "default": 10
                },
                "max_font_size": {
                    "description": "The max font size. Unit: px.",
                    "type": "number",
                    "default": 20
                },
                "max_opacity": {
                    "description": "The max opacity.",
                    "type": "number",
                    "default": 1
                },
                "min_opacity": {
                    "description": "The min opacity.",
                    "type": "number",
                    "default": 0.2
                },
                "max_level": {
                    "description": "The max level. Level: 1 ~ max_level.",
                    "type": "number",
                    "default": 10
                }
            },
            "additionalProperties": false,
            "required": ["min_font_size", "max_font_size", "min_opacity", "max_opacity", "max_level"]
        },

        "meta_generator": {
            "description": "Whether give metadata generator in <head>.",
            "type": "boolean",
            "default": true
        }
    },
    "required": [
        "title", "subtitle", "author", "lang", "menu",
        "posts_path", "archives_path", "categories_path", "tags_path",
        "tags_cloud",
        "post_per_page", "archives_post_per_page", "meta_generator"
    ],
    "additionalProperties": false
}

=== JoyWonderful/blog-data-recovery/src/config.json
{
    "$schema": "config.schema.json",

    "title": "Some Notes",
    "subtitle": "Be hard-working every day.",
    "author": "JoyWonderful",
    "license_default": "CC-BY-NC-4.0",
    "lang": "zh-CN",
    "favicon": "https://src-jywon.pages.dev/favicons/favicon-64-blog.png",
    "menu": [
        {
            "icon": "fa fa-home",
            "name": "首页",
            "href": "/"
        },
        {
            "icon": "fa fa-folder-tree",
            "name": "分类",
            "href": "/categories"
        },
        {
            "icon": "fa fa-tags",
            "name": "标签",
            "href": "/tags"
        },
        {
            "icon": "fa fa-box-archive",
            "name": "文章列表",
            "href": "/archives"
        }
    ],
    "menu_more": [
        {
            "icon": "fa fa-address-book",
            "name": "友情链接",
            "href": "/friends"
        },
        {
            "icon": "fa fa-comments",
            "name": "留言簿",
            "href": "/guestbook"
        },
        {
            "icon": "fa fa-info",
            "name": "关于",
            "href": "/about"
        }
    ],

    "posts_path": "/posts",
    "archives_path": "/archives",
    "categories_path": "/categories",
    "tags_path": "/tags",

    "post_per_page": 5,
    "archives_post_per_page": 10,

    "tags_cloud": {
        "min_font_size": 10,
        "max_font_size": 24,
        "max_opacity": 1,
        "min_opacity": 0.4,
        "max_level": 10
    },

    "meta_generator": true
}
